"""Speak and Reflection modules for LAMP."""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence

import numpy as np

from lamp.llm import BaseLLM
from lamp.llm.prompts import REFLECTION_SYSTEM_PROMPT, STATEMENT_SYSTEM_PROMPT

from .experience_pool import RetrievedExperience, summarize_observation
from .think import ThinkOutput


@dataclass
class SpeakConfig:
    """Configuration for statement generation and reflection."""

    n_candidates: int = 3
    max_context_items: int = 3


@dataclass(frozen=True)
class CandidateStatement:
    """One public statement candidate."""

    agent_id: int
    candidate_id: int
    text: str
    score: float


@dataclass(frozen=True)
class AgentReflection:
    """Reflection generated by one household after reading public statements."""

    agent_id: int
    text: str
    wealth_belief: list[str]
    trust: list[float]
    self_reflection: str


@dataclass(frozen=True)
class SpeakOutput:
    """Output of one Speak step."""

    candidate_statements: list[list[CandidateStatement]]
    selected_statements: list[str]
    reflections: list[AgentReflection]
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def reflection_texts(self) -> list[str]:
        return [reflection.text for reflection in self.reflections]

    @property
    def self_reflection_texts(self) -> list[str]:
        return [reflection.self_reflection for reflection in self.reflections]

    @property
    def trust_matrix(self) -> np.ndarray:
        return np.asarray([reflection.trust for reflection in self.reflections], dtype=np.float32)

    @property
    def wealth_beliefs(self) -> list[list[str]]:
        return [reflection.wealth_belief for reflection in self.reflections]


class StatementSelector:
    """Lightweight deterministic selector for candidate statements.

    The paper uses an attention-based selector. For the minimal reproduction, we
    score candidates by concise length and whether they mention useful economic
    action words. The interface can later be replaced by a neural selector.
    """

    action_words = ("savings", "labor", "wage", "consumption", "productivity", "investment")

    def score(self, statement: str) -> float:
        lower = statement.lower()
        action_score = sum(1.0 for word in self.action_words if word in lower)
        length_penalty = abs(len(statement.split()) - 16) * 0.03
        return action_score - length_penalty

    def select(self, candidates: Sequence[CandidateStatement]) -> CandidateStatement:
        if not candidates:
            raise ValueError("candidates cannot be empty")
        return max(candidates, key=lambda item: (item.score, -item.candidate_id))


class SpeakModule:
    """Generate public statements and peer reflections."""

    def __init__(
        self,
        llm: BaseLLM,
        config: SpeakConfig | None = None,
        selector: StatementSelector | None = None,
    ):
        self.llm = llm
        self.config = config or SpeakConfig()
        self.selector = selector or StatementSelector()

    def step(
        self,
        observation: Mapping[str, Any],
        think_output: ThinkOutput,
        experience_contexts: Mapping[int, Sequence[RetrievedExperience]] | None = None,
    ) -> SpeakOutput:
        """Run public statement generation and reflection for all agents."""

        private_obs = np.asarray(observation["private"], dtype=np.float32)
        n_agents = private_obs.shape[0]
        contexts = experience_contexts or {}

        all_candidates: list[list[CandidateStatement]] = []
        selected_statements: list[str] = []
        for agent_id in range(n_agents):
            candidates = self._generate_candidates(
                agent_id=agent_id,
                observation=observation,
                think_output=think_output,
                retrieved=contexts.get(agent_id, ()),
            )
            selected = self.selector.select(candidates)
            all_candidates.append(candidates)
            selected_statements.append(selected.text)

        reflections = [
            self._generate_reflection(
                agent_id=agent_id,
                observation=observation,
                think_output=think_output,
                selected_statements=selected_statements,
            )
            for agent_id in range(n_agents)
        ]

        return SpeakOutput(
            candidate_statements=all_candidates,
            selected_statements=selected_statements,
            reflections=reflections,
            metadata={"n_agents": n_agents, "n_candidates": self.config.n_candidates},
        )

    def _generate_candidates(
        self,
        agent_id: int,
        observation: Mapping[str, Any],
        think_output: ThinkOutput,
        retrieved: Sequence[RetrievedExperience],
    ) -> list[CandidateStatement]:
        candidates: list[CandidateStatement] = []
        for candidate_id in range(self.config.n_candidates):
            prompt = self._statement_prompt(
                agent_id=agent_id,
                candidate_id=candidate_id,
                observation=observation,
                think_output=think_output,
                retrieved=retrieved,
            )
            text = self.llm.generate(
                prompt,
                system_prompt=STATEMENT_SYSTEM_PROMPT,
                metadata={
                    "task": "statement",
                    "agent_id": agent_id,
                    "candidate_id": candidate_id,
                },
            ).text
            score = self.selector.score(text)
            candidates.append(
                CandidateStatement(
                    agent_id=agent_id,
                    candidate_id=candidate_id,
                    text=text,
                    score=score,
                )
            )
        return candidates

    def _generate_reflection(
        self,
        agent_id: int,
        observation: Mapping[str, Any],
        think_output: ThinkOutput,
        selected_statements: Sequence[str],
    ) -> AgentReflection:
        n_agents = len(selected_statements)
        reasoning = think_output.agent_reasonings[agent_id].text
        prompt = (
            f"agent_id: {agent_id}\n"
            f"private_reasoning: {reasoning}\n"
            f"public_statements:\n{self._format_statements(selected_statements)}\n"
            f"private_observation: {self._observation_summary(observation, agent_id)}"
        )
        text = self.llm.generate(
            prompt,
            system_prompt=REFLECTION_SYSTEM_PROMPT,
            metadata={"task": "reflection", "agent_id": agent_id, "n_agents": n_agents},
        ).text
        wealth_belief = self._parse_wealth_belief(text, n_agents)
        trust = self._parse_trust(text, n_agents)
        self_reflection = self._parse_self_reflection(text)
        return AgentReflection(
            agent_id=agent_id,
            text=text,
            wealth_belief=wealth_belief,
            trust=trust,
            self_reflection=self_reflection,
        )

    def _statement_prompt(
        self,
        agent_id: int,
        candidate_id: int,
        observation: Mapping[str, Any],
        think_output: ThinkOutput,
        retrieved: Sequence[RetrievedExperience],
    ) -> str:
        reasoning = think_output.agent_reasonings[agent_id].text
        context = self._format_retrieved(retrieved[: self.config.max_context_items])
        return (
            f"agent_id: {agent_id}\n"
            f"candidate_id: {candidate_id}\n"
            f"news_type: {think_output.news_type}\n"
            f"news: {think_output.news or 'No new public news.'}\n"
            f"private_reasoning: {reasoning}\n"
            f"retrieved_experience:\n{context}\n"
            f"private_observation: {self._observation_summary(observation, agent_id)}"
        )

    @staticmethod
    def _format_retrieved(retrieved: Sequence[RetrievedExperience]) -> str:
        if not retrieved:
            return "none"
        lines = []
        for idx, item in enumerate(retrieved, start=1):
            exp = item.experience
            lines.append(
                f"{idx}. score={item.score:.3f}, reward={exp.reward:.3f}, "
                f"reasoning={exp.reasoning}"
            )
        return "\n".join(lines)

    @staticmethod
    def _format_statements(statements: Sequence[str]) -> str:
        return "\n".join(f"agent_{idx}: {statement}" for idx, statement in enumerate(statements))

    @staticmethod
    def _observation_summary(observation: Mapping[str, Any], agent_id: int) -> str:
        return summarize_observation(
            observation.get("global_names", ()),
            observation["global"],
            observation.get("private_names", ()),
            observation["private"][agent_id],
        )

    @staticmethod
    def _parse_wealth_belief(text: str, n_agents: int) -> list[str]:
        match = re.search(r"wealth_belief\s*=\s*(\[[^\]]*\])", text)
        if match:
            try:
                values = ast.literal_eval(match.group(1))
                values = [str(value) for value in values]
                if len(values) == n_agents:
                    return values
            except (SyntaxError, ValueError):
                pass
        return ["mid"] * n_agents

    @staticmethod
    def _parse_trust(text: str, n_agents: int) -> list[float]:
        match = re.search(r"trust\s*=\s*(\[[^\]]*\])", text)
        if match:
            try:
                values = [float(value) for value in ast.literal_eval(match.group(1))]
                if len(values) == n_agents:
                    return values
            except (SyntaxError, ValueError, TypeError):
                pass
        return [5.0] * n_agents

    @staticmethod
    def _parse_self_reflection(text: str) -> str:
        match = re.search(r"self_reflection\s*=\s*([^.;]+)", text)
        if match:
            return match.group(1).strip()
        return text

